'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Package, ChevronRight, Play, RotateCcw, CheckCircle2, Circle, ArrowDown } from 'lucide-react';
import GlassCard from '@/components/ui/GlassCard';
import PageHeader from '@/components/layout/PageHeader';
import AnimatedSection from '@/components/ui/AnimatedSection';
import CodeBlock from '@/components/ui/CodeBlock';

const PHASES = [
  {
    phase: 'Loading',
    color: '#3B82F6',
    steps: [
      {
        id: 1, title: 'Find Binary Representation',
        description: 'The ClassLoader locates the .class file (from filesystem, JAR, network, or generated at runtime) using the fully-qualified class name.',
        detail: 'The search follows the parent-delegation model: Bootstrap → Platform → Application ClassLoader. Each ClassLoader checks its domain before delegating up.',
        code: `// Custom ClassLoader example
class URLClassLoader extends SecureClassLoader {
    @Override
    protected Class<?> findClass(String name) {
        byte[] bytes = loadClassData(name); // read .class bytes
        return defineClass(name, bytes, 0, bytes.length);
    }
}`,
        output: '.class bytes read into memory',
      },
      {
        id: 2, title: 'Parse Class File Structure',
        description: 'The JVM parses the binary format: magic number (0xCAFEBABE), version, constant pool, access flags, interfaces, fields, and methods.',
        detail: 'The constant pool stores symbolic references (class names, method signatures, string literals). At this stage references are symbolic — not yet resolved to actual memory addresses.',
        code: `// .class file structure (hex)
CA FE BA BE   // Magic number
00 00 00 41   // Major version 65 = Java 21
// Constant pool entries...
// Access flags, this class, superclass...`,
        output: 'Class structure parsed into JVM internal format',
      },
    ],
  },
  {
    phase: 'Linking',
    color: '#8B5CF6',
    steps: [
      {
        id: 3, title: 'Verification',
        description: 'The bytecode verifier performs structural and semantic checks to ensure the class is valid and safe to execute.',
        detail: 'Checks: valid bytecode instructions, operand stack does not overflow/underflow, type consistency of local variables, no illegal conversions, valid jump targets.',
        code: `// Verification checks (conceptual)
// 1. File format: magic, version, structure
// 2. Semantic: valid class hierarchy
// 3. Bytecode: operand stack depth consistency
// 4. Symbolic refs: valid descriptors
// JVM flag to skip (DANGEROUS): -Xverify:none`,
        output: 'Bytecode verified safe for execution',
      },
      {
        id: 4, title: 'Preparation',
        description: 'Memory is allocated for all static fields of the class, and they are initialized to their default zero values (not the values in your code).',
        detail: 'This is NOT the same as initialization. static int count = 10; — at this stage count becomes 0. The value 10 is assigned later during initialization.',
        code: `class Counter {
    static int count = 10;       // Preparation: count = 0
    static String name = "JVM";  // Preparation: name = null
    static boolean active = true;// Preparation: active = false
}
// Actual values assigned during Initialization phase`,
        output: 'Static fields set to default zero values',
      },
      {
        id: 5, title: 'Resolution',
        description: 'Symbolic references in the constant pool are replaced with direct references (memory pointers) to actual classes, fields, and methods.',
        detail: 'For example, a call to System.out.println() is initially a symbolic reference "java/io/PrintStream.println". Resolution replaces this with a direct pointer to the method. Resolution can be lazy (on first use) or eager.',
        code: `// Before resolution (symbolic):
//   CONSTANT_Methodref #42 → "java/lang/System.exit:(I)V"

// After resolution (direct reference):
//   Pointer to System.exit() method in Method Area

// Lazy resolution is the default — 
// a reference is resolved only when first used`,
        output: 'Symbolic references → direct memory references',
      },
    ],
  },
  {
    phase: 'Initialization',
    color: '#10B981',
    steps: [
      {
        id: 6, title: 'Execute <clinit>',
        description: 'The JVM executes the class initializer method <clinit>, which runs all static initializers and static field assignments in textual order.',
        detail: '<clinit> is generated by the compiler from static { } blocks and static field initializers. The JVM guarantees <clinit> is called exactly once per class, and it is synchronized — safe in multi-threaded scenarios.',
        code: `class Counter {
    static int count = 10;          // assigned in <clinit>
    static String name;
    static {
        name = "JVM";               // static initializer block
        System.out.println("Init"); // runs once
    }
}
// <clinit> runs when class is first actively used`,
        output: 'Static fields assigned + static blocks executed',
      },
    ],
  },
];

const ALL_STEPS = PHASES.flatMap((p) => p.steps.map((s) => ({ ...s, phase: p.phase, phaseColor: p.color })));

const classLoaders = [
  {
    name: 'Bootstrap ClassLoader',
    type: 'Native (C++)',
    color: '#3B82F6',
    loads: ['java.lang.*', 'java.util.*', 'java.io.*', 'javax.*', 'Core Java API (java.base module)'],
    description: 'The root ClassLoader — built into the JVM itself (not a Java class). Loads the fundamental Java API from the bootstrap classpath (jmods/java.base.jmod in Java 9+).',
  },
  {
    name: 'Platform ClassLoader',
    type: 'Java (since Java 9)',
    color: '#8B5CF6',
    loads: ['Java EE APIs', 'JDK extension modules', 'Named modules on the module path'],
    description: 'Replaced Extension ClassLoader in Java 9. Loads JDK platform classes not in java.base. Parent is Bootstrap ClassLoader.',
  },
  {
    name: 'Application ClassLoader',
    type: 'Java',
    color: '#10B981',
    loads: ['Your application code', 'Third-party JARs on classpath', 'Module path entries'],
    description: 'Loads classes from the application classpath (-cp or -classpath). This is the ClassLoader that loads your code. Its parent is the Platform ClassLoader.',
  },
  {
    name: 'Custom ClassLoader',
    type: 'Java (user-defined)',
    color: '#F59E0B',
    loads: ['Hot-reloaded classes', 'Classes from databases / networks', 'Dynamically generated bytecode', 'Encrypted class files'],
    description: 'Created by extending java.lang.ClassLoader and overriding findClass(). Used by application servers, OSGi, and frameworks that need custom class isolation or hot-reload.',
  },
];

export default function ClassLoaderPage() {
  const [currentStep, setCurrentStep] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [completed, setCompleted] = useState<Set<number>>(new Set());

  const step = ALL_STEPS[currentStep];

  const advance = () => {
    setCompleted((prev) => new Set([...prev, currentStep]));
    if (currentStep < ALL_STEPS.length - 1) setCurrentStep((s) => s + 1);
    else setIsPlaying(false);
  };

  const reset = () => { setCurrentStep(0); setCompleted(new Set()); setIsPlaying(false); };

  const playAll = async () => {
    setIsPlaying(true);
    for (let i = currentStep; i < ALL_STEPS.length; i++) {
      setCurrentStep(i);
      setCompleted((prev) => new Set([...prev, i]));
      await new Promise((r) => setTimeout(r, 1200));
    }
    setIsPlaying(false);
  };

  return (
    <div className="min-h-screen">
      <PageHeader
        badge="Class Loading"
        title="Class Loader"
        titleHighlight="Subsystem"
        description="Step through the three-phase lifecycle of class loading: Loading, Linking (Verify → Prepare → Resolve), and Initialization. See exactly what happens before your code runs."
        icon={Package}
        iconColor="#3B82F6"
        gradient="from-blue-400 via-indigo-400 to-purple-400"
      />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-24 space-y-10">

        {/* Parent Delegation visual */}
        <AnimatedSection>
          <GlassCard className="p-6">
            <h2 className="text-lg font-bold text-white mb-6">Parent-Delegation Model</h2>
            <div className="flex flex-col items-center gap-0">
              {classLoaders.map((cl, i) => (
                <div key={cl.name} className="flex flex-col items-center w-full max-w-lg">
                  <motion.div
                    initial={{ opacity: 0, y: 16 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: i * 0.1 }}
                    className="w-full rounded-xl border p-4"
                    style={{ borderColor: `${cl.color}40`, backgroundColor: `${cl.color}08` }}
                  >
                    <div className="flex items-start justify-between">
                      <div>
                        <p className="text-sm font-bold" style={{ color: cl.color }}>{cl.name}</p>
                        <p className="text-[10px] text-slate-500 mt-0.5">{cl.type}</p>
                      </div>
                      <div className="flex flex-wrap justify-end gap-1">
                        {cl.loads.slice(0, 2).map((l) => (
                          <span key={l} className="text-[9px] px-1.5 py-0.5 rounded border font-mono"
                            style={{ borderColor: `${cl.color}30`, color: `${cl.color}99`, backgroundColor: `${cl.color}10` }}>
                            {l}
                          </span>
                        ))}
                      </div>
                    </div>
                    <p className="text-xs text-slate-400 mt-2 leading-relaxed">{cl.description}</p>
                  </motion.div>
                  {i < classLoaders.length - 1 && (
                    <div className="flex flex-col items-center gap-1 py-1">
                      <ArrowDown className="w-4 h-4 text-slate-600" />
                      <span className="text-[9px] text-slate-600">delegates to</span>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </GlassCard>
        </AnimatedSection>

        {/* Step-through simulation */}
        <AnimatedSection delay={0.1}>
          <GlassCard className="overflow-hidden">
            <div className="flex items-center justify-between px-5 py-3 border-b border-white/[0.06]">
              <h2 className="text-sm font-bold text-white">Class Loading Lifecycle — Interactive Walkthrough</h2>
              <div className="flex items-center gap-2">
                <button
                  onClick={playAll}
                  disabled={isPlaying}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs bg-blue-600/20 border border-blue-500/30 text-blue-400 hover:bg-blue-600/30 transition-all disabled:opacity-50"
                >
                  <Play className="w-3 h-3" /> Auto-play
                </button>
                <button onClick={reset} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs border border-white/[0.08] text-slate-400 hover:text-white transition-all">
                  <RotateCcw className="w-3 h-3" /> Reset
                </button>
              </div>
            </div>

            <div className="grid lg:grid-cols-3 gap-0">
              {/* Step list */}
              <div className="border-r border-white/[0.06] p-4 space-y-1">
                {PHASES.map((phase) => (
                  <div key={phase.phase}>
                    <div className="text-[10px] uppercase tracking-widest font-semibold mb-2 mt-3 first:mt-0 px-2" style={{ color: phase.color }}>
                      {phase.phase}
                    </div>
                    {phase.steps.map((s) => {
                      const sIdx = ALL_STEPS.findIndex((x) => x.id === s.id);
                      const isCurrent = currentStep === sIdx;
                      const isDone = completed.has(sIdx);
                      return (
                        <button
                          key={s.id}
                          onClick={() => setCurrentStep(sIdx)}
                          className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-left transition-all ${
                            isCurrent ? 'bg-white/[0.06]' : 'hover:bg-white/[0.03]'
                          }`}
                        >
                          {isDone ? (
                            <CheckCircle2 className="w-4 h-4 shrink-0" style={{ color: phase.color }} />
                          ) : (
                            <Circle className={`w-4 h-4 shrink-0 ${isCurrent ? '' : 'text-slate-600'}`}
                              style={isCurrent ? { color: phase.color } : {}} />
                          )}
                          <span className={`text-xs ${isCurrent ? 'text-white font-medium' : 'text-slate-400'}`}>
                            {s.title}
                          </span>
                        </button>
                      );
                    })}
                  </div>
                ))}
              </div>

              {/* Step detail */}
              <div className="lg:col-span-2 p-6">
                <AnimatePresence mode="wait">
                  <motion.div
                    key={step.id}
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -12 }}
                    transition={{ duration: 0.2 }}
                  >
                    <div className="flex items-center gap-3 mb-4">
                      <span
                        className="text-xs px-2.5 py-1 rounded-full font-semibold"
                        style={{ backgroundColor: `${step.phaseColor}20`, color: step.phaseColor, border: `1px solid ${step.phaseColor}40` }}
                      >
                        {step.phase}
                      </span>
                      <h3 className="text-lg font-bold text-white">{step.title}</h3>
                    </div>

                    <p className="text-sm text-slate-300 mb-3 leading-relaxed">{step.description}</p>
                    <p className="text-xs text-slate-500 mb-5 leading-relaxed">{step.detail}</p>

                    <CodeBlock code={step.code} language="java" title={step.title} />

                    <div
                      className="mt-4 flex items-center gap-3 px-4 py-3 rounded-xl border text-sm"
                      style={{ borderColor: `${step.phaseColor}30`, backgroundColor: `${step.phaseColor}08` }}
                    >
                      <ChevronRight className="w-4 h-4 shrink-0" style={{ color: step.phaseColor }} />
                      <div>
                        <span className="text-xs text-slate-500 font-medium uppercase tracking-wider">Output: </span>
                        <span className="text-xs text-slate-300">{step.output}</span>
                      </div>
                    </div>

                    <div className="flex items-center justify-between mt-6">
                      <span className="text-xs text-slate-600">Step {currentStep + 1} / {ALL_STEPS.length}</span>
                      <button
                        onClick={advance}
                        disabled={currentStep === ALL_STEPS.length - 1}
                        className="flex items-center gap-2 px-5 py-2 rounded-xl text-sm font-medium bg-gradient-to-r from-blue-600 to-purple-600 text-white hover:from-blue-500 hover:to-purple-500 disabled:opacity-40 transition-all"
                      >
                        {currentStep === ALL_STEPS.length - 1 ? 'Complete' : 'Next Step'}
                        <ChevronRight className="w-4 h-4" />
                      </button>
                    </div>
                  </motion.div>
                </AnimatePresence>
              </div>
            </div>
          </GlassCard>
        </AnimatedSection>
      </div>
    </div>
  );
}
